apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
  namespace: animal-farm
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  gcePersistentDisk:
    pdName: animal-farm-disk
    fsType: ext4
  mountOptions:
    - uid=1000
    - gid=1000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
  namespace: animal-farm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi 