apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: animal-farm

resources:
- namespace.yaml
- frontend/deployment.yaml
- backend/deployment.yaml
- backend/persistence.yaml
- ingress.yaml
- frontend-config.yaml

configMapGenerator:
- name: backend-config
  literals:
  - NODE_ENV=production
  - DB_PATH=/app/data/db.sqlite 